---
# Tasks specific for OpenSuse Systems

- name: "Include Zabbix gpg ids"
  include_vars: zabbix.yml

- name: "Install zypper repo dependency"
  zypper:
    name: ["python-libxml2", "python-xml"]
    state: present
  become: yes
  register: zabbix_agent_package_dependency
  until: zabbix_agent_package_dependency is succeeded

- name: "Suse | Install basic repo file"
  zypper_repository:
    repo: "http://download.opensuse.org/repositories/server:/monitoring/SLE_11_SP3/server:monitoring.repo"
    name: "monitoring"
    state: present
  when:
    - zabbix_repo == "zabbix"
  become: yes
  tags:
    - zabbix-agent
    - init

- name: "Suse | Install zabbix-agent"
  zypper:
    name: "{{ zabbix_agent_packages }}"
    state: "{{ zabbix_agent_package_state }}"
    disable_gpg_check: yes
  register: zabbix_agent_package_installed
  until: zabbix_agent_package_installed is succeeded
  become: yes
  tags:
    - zabbix-agent
    - init
